### ISSUE TITLE
[Bug] The Project for the Reports command is hard to change

### ISSUE THREAD

**Issue by tdnzr** [JamesNZL/flow-toggl-plugin#115]
### Scenario

Navigate through the TogglTrack FlowLauncher plugin's `reports` command until you reach a specific project, like this:

`t reports day projects exercise`

(EDIT: Then press Enter.)

Then via the "backspace" key, try to delete the project and edit it to some other project, like "Habits", then press Enter:

`t reports day projects habits`

### Bug

Result: the FlowLauncher command is directly replaced with the previous command (the one with the "Exercise" project).

Things that don't help: Closing and re-opening the FlowLauncher input bar doesn't help. Deleting the entire command doesn't help. Even inputting a non-TogglTrack command doesn't help; once I paste the `t reports day projects habits` command, I again see the wrong `t reports day projects exercise` command.

Something that _does_ help is to input another TogglTrack command first. E.g.:

1) `t reports day projects exercise`

2) Random command, e.g. `t start` or `t reports day projects`.

3) `t reports day projects habits` -> Now this works.

**Comment by JamesNZL** [comment]
This is an interesting report—I can't reproduce. Are you able to take a screen recording of this happening (probably with some dummy time entries, if you don't want to use your real data)?

**Comment by tdnzr** [comment]
Hey there, apologies, I was missing a step (an 'Enter') in the reproduction description, which I've now edited in. [Here](https://i.imgur.com/yIJfYlJ.gif) is a gif of the resulting behavior.

**Comment by JamesNZL** [comment]
Ahh... I think I know what's happening there... because you're selecting the previous project and 'replacing' it immediately, it never goes into the blank `t reports day projects`, which is what resets the internal state...

I would always change project by `Ctrl + Backspace` to delete the entire word(s), then starting to type the new project (with the added assistance of fuzzy search + autocomplete).

Could I suggest you try to adopt this usage?

I can't remember if there was a deliberate design decision to persist the project until it resets completely (probably?), but that's how it is 😅

**Comment by tdnzr** [comment]
Ah, that makes sense. And as you say, there are ways to successfully reset the project. So I guess this issue can be closed then.
