### ISSUE TITLE
Misc. Feedback on v4.0.0

### ISSUE THREAD

**Issue by tdnzr** [JamesNZL/flow-toggl-plugin#116]
Follow-up to #28 and #90.

Hey there, once again apologies for the [very belasted feedback](https://github.com/JamesNZL/flow-toggl-plugin/issues/28#issuecomment-1653364594). Unfortunately, I'd made a mistake of promising to "systematically test the new command flow", which made this task seem so daunting that I actively procastinated on it^^. So this time I figured I'd just post what I notice within an hour.

### Usage
Regarding my recent usage of the plugin: I'm still using a bunch of different tools to enter time entries: mostly the desktop app, occasionally the FlowLauncher plugin, sometimes the mobile app. As mentioned previously, one pro of FlowLauncher over the desktop app is that the former interacts much better with Windows 11's virtual desktops. Whereas when the TogglTrack app is open in one of the other desktops, then clicking its taskbar icon switches my desktop right when I wanted to track time. So this causes a context switch and interruption right when I wanted to start tracking some productive activity.

Out of curiosity, how do you like the new command flow yourself? You mentioned you'd created this plugin because you didn't like the desktop app, so I imagine you've been using the new command flow a lot more than me.

### Feedback

- Notifications: From what I can tell, the new notification settings seem to work fine, in that I've disabled Success Notifications and now never see them again. Kudos!
- Usage Tips: I deactivated the Usage Tips, and I like how clean the plugin looks now when entering a time entry. I.e. there are only 2-3 FlowLauncher suggestions when I type `t take a walk`.
- UI: The one thing that (I think) doesn't work from my initial request is to auto-complete task entries via Tab, e.g. activate "take a walk" via "`tgl continue ta` -> Enter". That's because the "take a walk" entry is never the top-most entry. But that's fine, "`t ta` -> Alt + 3" works just as well.
- Command ordering: When starting TogglTrack, as long as the command field is empty (i.e. `t` or `t ` or `t         `), it would be neat if the other TogglTrack commands were a bit higher. Currently the top five results are "Start an empty time entry now", three Usage Tips, and the current running time entry. So all commands like "edit", "delete", "reports" etc. are offscreen. I figure some of those Usage Tips etc. don't need to appear until the potential time entry has at least one letter.
- Command ordering: When the command field partly matches a plugin command (like `t edi` for "edit"), then I see 20 time entries and only then the "edit" suggestion. I do like that "edit" is not appearing above the first time entry suggestion, but this priority level seems a bit low. Also,  in this situation, maybe the Usage Tips should be prioritised below the plugin commands.
- Command consistency: For "reports", the Usage Tip is "Use -[number] to view older reports". But this behavior only works for `day-5`, not `day -5`. Whereas for tasks it's *exactly the other way around*, i.e. only `<task> -t -5` works, but *not* `<task> -t-5` or `<task>-5 -t`.
- Command clarity: I wish the text in the FlowLauncher suggestions clearly separated the command text from the task description, e.g. via different text colors or brackets or something. E.g. instead of "Start take a walk now", it would be "Start 'take a walk' now" or "Start [take a walk] now" or similar. See [this screenshot](https://i.imgur.com/KnjC3A1.png).

**Comment by JamesNZL** [comment]
> Out of curiosity, how do you like the new command flow yourself? You mentioned you'd created this plugin because you didn't like the desktop app, so I imagine you've been using the new command flow a lot more than me.

Yeah, I *found* the new command flow to be essentially exactly what I was after—I never really found anything else I personally wanted to iterate after the latest release.

> I say 'found', as I've recently switched to the dark side of macOS—hence no longer use FlowLauncher/this plugin.  
> Consequently, I wouldn't really expect any further development on this plugin, at least from me.

## your feedback

1. Great!

2. :)

3. Yeah, there's a few factors at play here—one is that whichever description is the closest fuzzy match will naturally be prioritised, but there is *also* FlowLauncher's internal ranking system that will prioritise the results that you use more frequently. This process is quite opaque, and can take some time to 'train'—and is also a reason why it is difficult (and discouraged) to manually enforce a given ordering.

4. This is partially addressed by the above, but, I'd personally argue that an empty command bar is *exactly* when you need those Usage Tips—I believe it was you? that said the initial flow was unintuitive, and there needed to be some prompt for new users to understand. Apologies if this wasn't you, but, just illustrating that this was to address a user request :)

5. Again, this unfortunately isn't really something that I can manually enforce due to FL's internal rankings. I also would suggest this isn't a problem, as typing `t edit ` will automatically trigger the `edit` command, and is *way* faster than the user looking down the list and selecting/clicking the `edit` result.

6. Fair criticism, and one whose answer would be an implementation detail rather than a design decision (in all honesty, these things were added quite far apart from each other, and the entire `reports` command flow was always a very separate thing in my head—hence why I never made the connection :^))

7. Hm, that's a good suggestion. I didn't add this at first to save characters, but I don't see why this can't be a setting for the user to decide—let me know if you find this particularly desirable; I think it should be a pretty easy feature that I can find some time to add.

**Comment by tdnzr** [comment]
I'm glad to hear that you were happy with the new architecture we discussed!

> I say 'found', as I've recently switched to the dark side of macOS—hence no longer use FlowLauncher/this plugin.
Consequently, I wouldn't really expect any further development on this plugin, at least from me.

Haha, no worries :). I wish you a good experience with macOS! I've never regretted being on Windows/Android, rather than macOS, until I wanted to buy a health tracker and learned how much worse (particularly in accuracy, but also in UI, app support, etc.) even the best Android smartwatches are vs. the Apple ones =(.

Re: 4, that might well have been me, my memory is just bad T_T.

Re: 7, I would find this feature genuinely desirable, but not if it requires any meaningful effort on your part to implement. Anyway, I figured FlowLauncher plugins would have some ability to display themed colors in FlowLauncher commands, but maybe they don't? If not, maybe just insert two quotation marks, i.e. display commands like `Start take a walk now` as `Start "take a walk" now`.

--

Finally, since my original post I've noticed another point where your FlowLauncher plugin feels better than the native TogglTrack app: The latter only autocompletes entries from the last 1-2 months. I try to keep my time entry phrasing consistent over time, and for rare time entries this is *much* easier via the FlowLauncher plugin since its autocomplete covers more than just the recent ones.

**Comment by JamesNZL** [comment]
> I wish you a good experience with macOS! I've never regretted being on Windows/Android, rather than macOS, until I wanted to buy a health tracker...

Hahah, cheers! Definitely loving it so far (macOS less... but I've hit it with [yabai](https://github.com/koekeishiya/yabai) sufficiently hard that it's submitted to my desires 😂).
Was ultimately a decision motivated by hardware; I couldn't resist the quality/efficiency of Apple Silicon any longer lol.

> I would find this feature genuinely desirable, but not if it requires any meaningful effort on your part to implement.

I don't expect it to... I've added it to my to-do list, I reckon I'll manage to find some time to implement & release this long weekend...

> I figured FlowLauncher plugins would have some ability to display themed colors in FlowLauncher commands

I vaguely remember playing around with something like this (possibly `Result.TitleHighlightData` in the [API docs](https://www.flowlauncher.com/docs/#/API-Reference/Flow.Launcher.Plugin/Result)?) but IIRC it was either sketchy/ugly/deprecated/otherwise undesirable.

I'll have another try, and fallback to quotes if needed.

> The latter only autocompletes entries from the last 1-2 months. I try to keep my time entry phrasing consistent over time, and for rare time entries this is _much_ easier via the FlowLauncher plugin since its autocomplete covers more than just the recent ones.

YES; I'm glad you noticed—this is also a _massive_ thing for me, and frustrates me to no end with the Toggl first-party interfaces and even [Timery](https://timeryapp.com/), the otherwise-stellar alternative I'm using on my MacBook. Having to run a report to try to find a previous description is frustrating as hell.

I can't remember if the autocomplete covers the last 366 days (Toggl's single-request API limit), or if it's extra keen and tries to paginate until nothing is found... either, it's much better 😛

**Comment by tdnzr** [comment]
> YES; I'm glad you noticed—this is also a _massive_ thing for me, and frustrates me to no end with the Toggl first-party interfaces and even [Timery](https://timeryapp.com/), the otherwise-stellar alternative I'm using on my MacBook. Having to run a report to try to find a previous description is frustrating as hell.
> 
> I can't remember if the autocomplete covers the last 366 days (Toggl's single-request API limit), or if it's extra keen and tries to paginate until nothing is found... either, it's much better 😛

This one might warrant being listed as a [Feature in the Github readme](https://github.com/JamesNZL/flow-toggl-plugin?tab=readme-ov-file#features). Something like "auto-complete even for non-recent time entries", or a more eloquent phrasing of that. Or maybe just "more comprehensive auto-complete".

**Comment by JamesNZL** [comment]
Good idea, thanks!

**Comment by JamesNZL** [comment]
Closing in favour of #117.
